spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      #  create	기존테이블을 삭제하고 다시 생성
      #  create-drop 기존테이블을 삭제하고 다시생성. 종료 시점에 테이블삭제
      #  update	변경된 스키마 적용 (운영 DB 에서 사용X)
      #  validate Entity 와 테이블이 정상 매핑 되었는지 확인
      #  none 기존테이블을 더 이상 건드리지 않음.
    properties:
      hibernate:
        #        show_sql: true
        format_sql: false
        default_batch_fetch_size: 1000 #최적화 옵션
    open-in-view: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging.level:
  org:
  hibernate:
    SQL: error
  root: INFO
  com.your.package: DEBUG
#  org.hibernate.type: trace